### ISSUE TITLE
Variety season template use

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/terraprobe#162]
Hi Byron,

Was the variety season template designed to change all the sites associated with that variety?
For example if a variety say 'rockit' harvested as a variety 2 weeks earlier than normal could we use the template to alter all the sites with  'Rockit' varieties rather that doing each manually? 
![image](https://user-images.githubusercontent.com/50975792/93527295-bf649880-f98c-11ea-8d21-62c2b9dac555.png)

**Comment by mabbettbyron** [comment]
Hi Brendan,
I think we need to catch up on this. Would like to implement now but need to discuss a couple of gotchas with you. Maybe next week

**Comment by mabbettbyron** [comment]
DELETED
