### ISSUE TITLE
Recommendation review submit mesage

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/terraprobe#215]
Hi Byron,

Started getting the message below when submitting the recommendation review.
Everything is returning reviewed 'true' and all goes through to portal still.

![image](https://user-images.githubusercontent.com/50975792/107686777-839ae880-6d0a-11eb-8fce-2e9b211b5f62.png)

**Comment by mabbettbyron** [comment]
Hi Brendan,
This is timing out after one minute with communication with dashboard. Will contact Mike about it to see what can be done.

It might be you went from reviewing 5 or 6 times a day to a big one of at end of day?

Cheers
Byron

**Comment by mabbettbyron** [comment]
Hi Mike,Long time no catch up. Hope it is all going well in the New Year for you and Hortplus.
I tried the slack channel but not up.
A call by terraprobe to an endpoint on the dashboard is taking over a minute to respond. Was wondering if it's just doing a lot of work on your end and could be streamlined, or I could do something at Terraprobe end to handle it. To be honest the Fruition guys don't really look at the output in the response that the Terraprobe webserver is waiting for.
2021-02-04 16:37:07,303 skeleton.views DEBUG    post to url https://api.properties.hortplus.com/api/send-reports/irrigation
2021-02-04 16:37:08,380 skeleton.views DEBUG    {'service': 'fruition', 'sites': [{'id': 14}, {'id': 363}, {'id': 362}, {'id': 361}, {'id': 360}, {'id': 359}, {'id': 347}, {'id': 346}, {'id': 508}, {'id': 337}, 
{'id': 336}, {'id': 335}, {'id': 334}, {'id': 333}, {'id': 332}, {'id': 331}, {'id': 330}, {'id': 325}, {'id': 324}, {'id': 7}, {'id': 8}, {'id': 9}, {'id': 10}, {'id': 2}, {'id': 3}, {'id': 4}, {'id': 5}, {'id'
: 6}, {'id': 11}, {'id': 12}, {'id': 1}, {'id': 293}, {'id': 292}, {'id': 291}, {'id': 281}, {'id': 280}, {'id': 279}, {'id': 13}, {'id': 482}, {'id': 483}, {'id': 484}, {'id': 485}, {'id': 238}, {'id': 236}, {'
id': 235}, {'id': 15}, {'id': 190}, {'id': 189}, {'id': 188}, {'id': 187}, {'id': 186}, {'id': 185}, {'id': 184}, {'id': 183}, {'id': 174}, {'id': 173}, {'id': 172}, {'id': 171}, {'id': 170}, {'id': 147}, {'id':
 146}, {'id': 145}, {'id': 144}, {'id': 143}, {'id': 142}, {'id': 141}, {'id': 140}, {'id': 139}, {'id': 138}, {'id': 137}, {'id': 136}, {'id': 135}, {'id': 134}, {'id': 133}, {'id': 461}, {'id': 460}, {'id': 45
9}, {'id': 458}, {'id': 457}, {'id': 128}, {'id': 127}, {'id': 126}, {'id': 454}, {'id': 453}, {'id': 452}, {'id': 451}, {'id': 125}, {'id': 124}, {'id': 123}, {'id': 122}, {'id': 121}, {'id': 120}, {'id': 119},
 {'id': 118}, {'id': 117}, {'id': 109}, {'id': 531}, {'id': 108}, {'id': 18}, {'id': 17}, {'id': 16}, {'id': 500}, {'id': 434}, {'id': 416}, {'id': 410}, {'id': 409}, {'id': 408}, {'id': 407}, {'id': 406}, {'id'
: 405}, {'id': 404}, {'id': 403}, {'id': 402}, {'id': 397}, {'id': 396}, {'id': 395}, {'id': 394}, {'id': 393}, {'id': 388}, {'id': 387}, {'id': 384}, {'id': 383}, {'id': 382}, {'id': 381}, {'id': 379}, {'id': 3
74}, {'id': 373}, {'id': 372}, {'id': 370}, {'id': 369}, {'id': 368}, {'id': 367}, {'id': 510}, {'id': 511}, {'id': 514}, {'id': 515}, {'id': 516}]}
2021-02-04 16:37:08,381 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.properties.hortplus.com
2021-02-04 16:38:08,469 urllib3.connectionpool DEBUG    https://api.properties.hortplus.com:443 "POST /api/send-reports/irrigation HTTP/1.1" 504 160

CheersByron
