### ISSUE TITLE
Summary Report

### ISSUE THREAD

**Issue by angusbews** [mahalsnz/terraprobe#232]
EOY - Summary graphs are not copying over correctly, the "Harvest", "Post-Harvest" critical dates are wrong and is skewering the graph
![image](https://user-images.githubusercontent.com/84684909/122690674-14686e80-d27f-11eb-910f-4f5f7ebc73c9.png)

**Comment by mabbettbyron** [comment]
This was a big problem affecting all reports. Have fixed now but please give all summary graphs a good look. Was a big fix so may have broken something else.

**Comment by angusbews** [comment]
Seems to have fixed the summary graphs, will investigate outcome further
