### ISSUE TITLE
Reports Not Processing

### ISSUE THREAD

**Issue by angusbews** [mahalsnz/terraprobe#233]
Reports that are not processing:
HB:
- T&G Eveenden
- Bostock Maraekakaho
- Bostock Tullamain
- Rockit Home Block
- Rockit West
- Mr Apple Crawley
- Mr Apple Powdrell
CHB:
- Mr Apple Rangihau

**Comment by mabbettbyron** [comment]
Report was trying to include inactive sites. All those reports should be working now.

**Comment by angusbews** [comment]
All working fine now
