### ISSUE TITLE
Soil profile chart

### ISSUE THREAD

**Issue by AlexHoek** [mahalsnz/terraprobe#237]
With the addition of the fuel gauge the soil profile chart appears to have 'shrunk' and it no longer lines up with the VSW% by depth chart that it sits next to.  

See how in the below snip the bottom of the soil profile chart finishes in line with around 90cm on the VSW% chart, rather than extending the full length.

Cheers.

![image](https://user-images.githubusercontent.com/87505377/125873494-b60e770c-d2f2-4110-9797-51386c9c3ccb.png)
 
@mabznz

**Comment by mabbettbyron** [comment]
**All Done 1 hour**
